### PR TITLE
Update for Ruby 2.4

### PR DESCRIPTION
**Pull request by technion**
I'm unsure if you're still maintaining this Gem, but I've been using it right up until Ruby 2.4 broke it. Fixes:

* Remove reference to FixNum class as it no longer exists
* Update RSpec as version on Gemfile not compatible
* Update test format because [this code](https://github.com/lomereiter/ruby-numtheory/blob/master/spec/numtheory/primality_tests_spec.rb#L3) seemed to stop doing anything and I got tonnes of deprecation warnings anyway.

### CODE REVIEW

**Comment by technion** [comment]
Note sure what that CI failure's about but it seems to refer to bits of code I never touched in Ruby 2.0 only.

**Comment by lomereiter** [comment]
Thanks a lot! Please add 2.4 to the build matrix otherwise CI doesn't make much sense.

**Comment by lomereiter** [comment]
Regarding the fail on Travis, they now use Clang compiler for 2.0, and it doesn't accept same ASM constructs as GCC: https://bugs.llvm.org//show_bug.cgi?id=10365
Changing '%cc' to just 'cc' in reduce.c should fix it.

**Comment by technion** [comment]
Thanks for that tip - I've added a commit which fixes the CI.

**Comment by lomereiter** [comment]
Cool, thanks!

**Pull request merged**
